# Generated by Django 2.1.4 on 2019-01-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa Kategorii')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa Materiału')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena (PLN)')),
                ('description', models.TextField(blank=True, verbose_name='Opis Materiału')),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Obraz gółwny')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Obraz 2')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Obraz 3')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Obraz 4')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Obraz 5')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Category')),
            ],
            options={
                'verbose_name': 'Materiał',
                'verbose_name_plural': 'Materiały',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa produktu')),
                ('price_lm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena mb (PLN)')),
                ('price_m2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena m^2 (PLN)')),
                ('thickness', models.IntegerField(verbose_name='Gruboość (mm)')),
                ('width', models.IntegerField(verbose_name='Szerokość (mm)')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Waga')),
                ('material', models.CharField(max_length=100, verbose_name='Materiał')),
                ('kind', models.CharField(blank=True, max_length=10, verbose_name='Gatunek')),
                ('description', models.TextField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Obraz gółwny')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Obraz 2')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Obraz 3')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Obraz 4')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Obraz 5')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Category')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
    ]
