# Generated by Django 2.1.4 on 2019-01-13 12:05

from django.db import migrations, models
import django.db.models.deletion
import materials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nazwa Materiału')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena (PLN)')),
                ('description', models.TextField(blank=True, verbose_name='Opis Materiału')),
                ('photo_main', models.ImageField(upload_to=materials.models.get_upload_path, verbose_name='Obraz gółwny')),
                ('photo_2', models.ImageField(blank=True, upload_to=materials.models.get_upload_path, verbose_name='Obraz 2')),
                ('photo_3', models.ImageField(blank=True, upload_to=materials.models.get_upload_path, verbose_name='Obraz 3')),
                ('photo_4', models.ImageField(blank=True, upload_to=materials.models.get_upload_path, verbose_name='Obraz 4')),
                ('photo_5', models.ImageField(blank=True, upload_to=materials.models.get_upload_path, verbose_name='Obraz 5')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.MaterialCategory', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Akcesoria',
                'verbose_name_plural': 'Akcesoria',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa produktu')),
                ('price_lm', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena mb (PLN)')),
                ('price_m2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena m² (PLN)')),
                ('thickness', models.IntegerField(verbose_name='Gruboość (mm)')),
                ('width', models.IntegerField(verbose_name='Szerokość (mm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Waga')),
                ('material', models.CharField(max_length=100, verbose_name='Materiał')),
                ('kind', models.CharField(blank=True, max_length=100, verbose_name='Gatunek')),
                ('description', models.TextField(blank=True, verbose_name='Opis produktu')),
                ('used_for_calculate', models.BooleanField(default=True, verbose_name='Pokaż w kalkulatorze')),
                ('photo_main', models.ImageField(upload_to=materials.models.get_upload_path, verbose_name='Obraz gółwny')),
                ('photo_2', models.ImageField(blank=True, upload_to=materials.models.get_upload_path, verbose_name='Obraz 2')),
                ('photo_3', models.ImageField(blank=True, upload_to=materials.models.get_upload_path, verbose_name='Obraz 3')),
                ('photo_4', models.ImageField(blank=True, upload_to=materials.models.get_upload_path, verbose_name='Obraz 4')),
                ('photo_5', models.ImageField(blank=True, upload_to=materials.models.get_upload_path, verbose_name='Obraz 5')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.ProductCategory', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
    ]
