# Generated by Django 2.1.4 on 2019-01-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('assembly_typ', models.CharField(max_length=100, verbose_name='Typ zabudowy')),
                ('price_m2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cena m² (PLN)')),
                ('description', models.TextField(blank=True, verbose_name='Opis produktu')),
            ],
            options={
                'verbose_name': 'Typ montażu',
                'verbose_name_plural': 'Typy montażu',
            },
        ),
    ]
