# Generated by Django 2.1.4 on 2019-01-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa Kategorii')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategoria Materiału',
                'verbose_name_plural': 'Kategorie Materiałów',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa Kategorii')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategoria Produktu',
                'verbose_name_plural': 'Kategorie Produktów',
            },
        ),
        migrations.CreateModel(
            name='RealizationCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa Kategorii')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kategoria Realizacji',
                'verbose_name_plural': 'Kategorie Realizacji',
            },
        ),
    ]
