# Generated by Django 2.1.4 on 2019-01-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='product_type',
            field=models.IntegerField(choices=[('3', 'Inne'), ('1', 'Deski'), ('2', 'Drewno Konstrukcyjne')], default=1, verbose_name='Typ'),
            preserve_default=False,
        ),
    ]
