# Generated by Django 2.1.4 on 2019-01-13 12:05

from django.db import migrations, models
import django.db.models.deletion
import realizations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('calculations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ralization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Tytuł realizacji')),
                ('cost', models.IntegerField(verbose_name='Koszt realizacji (PLN)')),
                ('area', models.DecimalField(decimal_places=1, max_digits=8, verbose_name='Powierzchnia m²')),
                ('location', models.CharField(max_length=100, verbose_name='Lokalizacja')),
                ('description', models.TextField(blank=True, verbose_name='Opis realizacji')),
                ('realization_time', models.IntegerField(verbose_name='Czas realizacji (dni)')),
                ('realization_date', models.DateField(verbose_name='Termin realizacji')),
                ('photo_main', models.ImageField(upload_to=realizations.models.get_upload_realization_path, verbose_name='Obraz gółwny')),
                ('photo_2', models.ImageField(blank=True, upload_to=realizations.models.get_upload_realization_path, verbose_name='Obraz 2')),
                ('photo_3', models.ImageField(blank=True, upload_to=realizations.models.get_upload_realization_path, verbose_name='Obraz 3')),
                ('photo_4', models.ImageField(blank=True, upload_to=realizations.models.get_upload_realization_path, verbose_name='Obraz 4')),
                ('photo_5', models.ImageField(blank=True, upload_to=realizations.models.get_upload_realization_path, verbose_name='Obraz 5')),
                ('assembly_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='calculations.Assembly', verbose_name='Typ zabudowy')),
                ('used_materials1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_materials1', to='materials.Material', verbose_name='Użyte materiały (1)')),
                ('used_materials2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_materials2', to='materials.Material', verbose_name='Użyte materiały (2)')),
                ('used_materials3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_materials3', to='materials.Material', verbose_name='Użyte materiały (3)')),
                ('used_products1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_products1', to='materials.Product', verbose_name='Użyte produkty (1)')),
                ('used_products2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_products2', to='materials.Product', verbose_name='Użyte produkty (2)')),
                ('used_wood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_wood', to='materials.Product', verbose_name='Użyte drewno')),
            ],
            options={
                'verbose_name': 'Realizacja',
                'verbose_name_plural': 'Realizacje',
            },
        ),
    ]
