# Generated by Django 2.1.4 on 2019-01-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('realizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ralization',
            name='category_name',
            field=models.ManyToManyField(to='categories.RealizationCategory', verbose_name='Kategoria'),
        ),
    ]
